CREATE TYPE region AS ENUM ('BATKEN', 'OSH', 'JALAL_ABAD', 'BISHKEK', 'TALAS', 'CHUI', 'YSYK_KOL', 'NARYN');
CREATE TYPE house_type AS ENUM ('APARTMENT', 'HOUSE');
CREATE TYPE house_state AS ENUM ('ACCEPTED', 'REJECTED', 'PENDING');
CREATE TYPE user_role AS ENUM ('USER', 'ADMIN');